##########################################################################
# Title:            Saltbox Mod: Calibre-Web Automated                   #
# Author(s):        Derek                                                #
# URL:              https://github.com/saltyorg/Saltbox_mod              #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

calibre_web_automated_name: calibre_web_automated

################################
# Paths
################################

calibre_web_automated_role_ingest_path: "/mnt/unionfs/Media/Books/ingest"
calibre_web_automated_role_library_path: "/mnt/unionfs/Media/Books/library"
calibre_web_automated_role_paths_folder: "{{ calibre_web_automated_name }}"
calibre_web_automated_role_paths_location: "{{ server_appdata_path }}/{{ calibre_web_automated_role_paths_folder }}"
calibre_web_automated_role_cache_path: "{{ calibre_web_automated_role_paths_location }}/cache"
calibre_web_automated_role_paths_folders_list_default:
  - "{{ lookup('role_var', '_paths_location', role='calibre_web_automated') }}"
  - "{{ lookup('role_var', '_paths_location', role='calibre_web_automated') }}/config"
  - "{{ lookup('role_var', '_cache_path', role='calibre_web_automated') }}"
  - "{{ lookup('role_var', '_ingest_path', role='calibre_web_automated') }}"
  - "{{ lookup('role_var', '_library_path', role='calibre_web_automated') }}"
calibre_web_automated_role_paths_folders_list_custom: []
calibre_web_automated_role_paths_folders_list: "{{ lookup('role_var', '_paths_folders_list_default', role='calibre_web_automated')
                                                + lookup('role_var', '_paths_folders_list_custom', role='calibre_web_automated') }}"

################################
# Web
################################

calibre_web_automated_role_web_subdomain: "cwa"
calibre_web_automated_role_web_domain: "{{ user.domain }}"
calibre_web_automated_role_web_port: "8083"
calibre_web_automated_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='calibre_web_automated') + '.' + lookup('role_var', '_web_domain', role='calibre_web_automated')
                                     if (lookup('role_var', '_web_subdomain', role='calibre_web_automated') | length > 0)
                                     else lookup('role_var', '_web_domain', role='calibre_web_automated')) }}"

################################
# DNS
################################

calibre_web_automated_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='calibre_web_automated') }}"
calibre_web_automated_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='calibre_web_automated') }}"
calibre_web_automated_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

calibre_web_automated_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
calibre_web_automated_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
calibre_web_automated_role_traefik_middleware_custom: ""
calibre_web_automated_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
calibre_web_automated_role_traefik_enabled: true
calibre_web_automated_role_traefik_api_enabled: false
calibre_web_automated_role_traefik_api_endpoint: ""

################################
# THEME
################################

calibre_web_automated_role_themepark_enabled: false
calibre_web_automated_role_themepark_theme: "{{ global_themepark_theme }}"
calibre_web_automated_role_themepark_domain: "{{ global_themepark_domain }}"

################################
# Docker
################################

calibre_web_automated_role_docker_container: "{{ calibre_web_automated_name }}"

# Image
calibre_web_automated_role_docker_image_pull: true
calibre_web_automated_role_docker_image_tag: "latest"
calibre_web_automated_role_docker_image_repo: "crocodilestick/calibre-web-automated"
calibre_web_automated_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='calibre_web_automated') }}:{{ lookup('role_var', '_docker_image_tag', role='calibre_web_automated') }}"

# Ports
calibre_web_automated_role_docker_ports_defaults: []
calibre_web_automated_role_docker_ports_custom: []
calibre_web_automated_role_docker_ports: "{{ lookup('role_var', '_docker_ports_defaults', role='calibre_web_automated')
                                          + lookup('role_var', '_docker_ports_custom', role='calibre_web_automated') }}"

# Envs
calibre_web_automated_role_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"

calibre_web_automated_role_docker_envs_custom: {}
calibre_web_automated_role_docker_envs_theme:
  DOCKER_MODS: "linuxserver/mods:universal-calibre|ghcr.io/themepark-dev/theme.park:calibre-web"
  TP_DOMAIN: "{{ lookup('role_var', '_themepark_domain', role='calibre_web_automated') }}"
  TP_THEME: "{{ lookup('role_var', '_themepark_theme', role='calibre_web_automated') }}"

calibre_web_automated_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='calibre_web_automated')
                                          | combine(lookup('role_var', '_docker_envs_custom', role='calibre_web_automated'))
                                          if not (lookup('role_var', '_themepark_enabled', role='calibre_web_automated'))
                                          else lookup('role_var', '_docker_envs_default', role='calibre_web_automated')
                                          | combine(lookup('role_var', '_docker_envs_custom', role='calibre_web_automated'))
                                          | combine(calibre_web_automated_role_docker_envs_theme) }}"

# Commands
calibre_web_automated_role_docker_commands_default: []
calibre_web_automated_role_docker_commands_custom: []
calibre_web_automated_role_docker_commands: "{{ lookup('role_var', '_docker_commands_default', role='calibre_web_automated')
                                             + lookup('role_var', '_docker_commands_custom', role='calibre_web_automated') }}"

# Volumes
calibre_web_automated_role_docker_volumes_default:
  - "{{ lookup('role_var', '_paths_location', role='calibre_web_automated') }}/config:/config"
  - "{{ lookup('role_var', '_cache_path', role='calibre_web_automated') }}:/cache"
  - "{{ lookup('role_var', '_library_path', role='calibre_web_automated') }}:/calibre-library"
  - "{{ lookup('role_var', '_ingest_path', role='calibre_web_automated') }}:/cwa-book-ingest"
calibre_web_automated_role_docker_volumes_custom: []
calibre_web_automated_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='calibre_web_automated')
                                            + lookup('role_var', '_docker_volumes_custom', role='calibre_web_automated')
                                            + docker_volumes_downloads_common }}"

# Devices
calibre_web_automated_role_docker_devices_default: []
calibre_web_automated_role_docker_devices_custom: []
calibre_web_automated_role_docker_devices: "{{ lookup('role_var', '_docker_devices_default', role='calibre_web_automated')
                                            + lookup('role_var', '_docker_devices_custom', role='calibre_web_automated') }}"

# Hosts
calibre_web_automated_role_docker_hosts_default: {}
calibre_web_automated_role_docker_hosts_custom: {}
calibre_web_automated_role_docker_hosts: "{{ docker_hosts_common
                                          | combine(lookup('role_var', '_docker_hosts_default', role='calibre_web_automated'))
                                          | combine(lookup('role_var', '_docker_hosts_custom', role='calibre_web_automated')) }}"

# Labels
calibre_web_automated_role_docker_labels_default: 
  traefik.http.middlewares.kobo-sync-headers.headers.customrequestheaders.X-Scheme: "https"
calibre_web_automated_role_docker_labels_custom: {}
calibre_web_automated_role_docker_labels: "{{ docker_labels_common
                                           | combine(lookup('role_var', '_docker_labels_default', role='calibre_web_automated'))
                                           | combine(lookup('role_var', '_docker_labels_custom', role='calibre_web_automated')) }}"

# Hostname
calibre_web_automated_role_docker_hostname: "{{ calibre_web_automated_name }}"

# Networks
calibre_web_automated_role_docker_networks_alias: "{{ calibre_web_automated_name }}"
calibre_web_automated_role_docker_networks_default: []
calibre_web_automated_role_docker_networks_custom: []
calibre_web_automated_role_docker_networks: "{{ docker_networks_common
                                             + lookup('role_var', '_docker_networks_default', role='calibre_web_automated')
                                             + lookup('role_var', '_docker_networks_custom', role='calibre_web_automated') }}"

# Capabilities
calibre_web_automated_role_docker_capabilities_default: []
calibre_web_automated_role_docker_capabilities_custom: []
calibre_web_automated_role_docker_capabilities: "{{ lookup('role_var', '_docker_capabilities_default', role='calibre_web_automated')
                                                 + lookup('role_var', '_docker_capabilities_custom', role='calibre_web_automated') }}"

# Security Opts
calibre_web_automated_role_docker_security_opts_default: []
calibre_web_automated_role_docker_security_opts_custom: []
calibre_web_automated_role_docker_security_opts: "{{ lookup('role_var', '_docker_security_opts_default', role='calibre_web_automated')
                                                  + lookup('role_var', '_docker_security_opts_custom', role='calibre_web_automated') }}"

# Restart Policy
calibre_web_automated_role_docker_restart_policy: unless-stopped

# State
calibre_web_automated_role_docker_state: started
