##########################################################################
# Title:            Saltbox Mod: Calibre-Web Automated Book Downloader   #
# Author(s):        Derek                                                #
# URL:              https://github.com/saltyorg/Saltbox_mod              #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

calibre_web_automated_downloader_name: calibre_web_automated_downloader

################################
# Settings
################################

calibre_web_automated_downloader_role_book_language: "en"
calibre_web_automated_downloader_role_cwa_db_path: "{{ lookup('role_var', '_paths_location', role='calibre_web_automated', default=(server_appdata_path + '/calibre_web_automated')) }}/config/app.db"
calibre_web_automated_downloader_role_ingest_path: "{{ lookup('role_var', '_ingest_path', role='calibre_web_automated', default='/mnt/unionfs/Media/Books/ingest') }}"

################################
# Paths
################################

calibre_web_automated_downloader_role_paths_folder: "{{ calibre_web_automated_downloader_name }}"
calibre_web_automated_downloader_role_paths_location: "{{ server_appdata_path }}/{{ calibre_web_automated_downloader_role_paths_folder }}"
calibre_web_automated_downloader_role_paths_folders_list_default:
  - "{{ lookup('role_var', '_paths_location', role='calibre_web_automated_downloader') }}"
  - "{{ lookup('role_var', '_ingest_path', role='calibre_web_automated_downloader') }}"
calibre_web_automated_downloader_role_paths_folders_list_custom: []
calibre_web_automated_downloader_role_paths_folders_list: "{{ lookup('role_var', '_paths_folders_list_default', role='calibre_web_automated_downloader')
                                                           + lookup('role_var', '_paths_folders_list_custom', role='calibre_web_automated_downloader') }}"

################################
# Web
################################

calibre_web_automated_downloader_role_web_subdomain: "cwad"
calibre_web_automated_downloader_role_web_domain: "{{ user.domain }}"
calibre_web_automated_downloader_role_web_port: "8084"
calibre_web_automated_downloader_role_web_url: "{{ 'https://' + (lookup('role_var', '_web_subdomain', role='calibre_web_automated_downloader') + '.' + lookup('role_var', '_web_domain', role='calibre_web_automated_downloader')
                                                if (lookup('role_var', '_web_subdomain', role='calibre_web_automated_downloader') | length > 0)
                                                else lookup('role_var', '_web_domain', role='calibre_web_automated_downloader')) }}"

################################
# DNS
################################

calibre_web_automated_downloader_role_dns_record: "{{ lookup('role_var', '_web_subdomain', role='calibre_web_automated_downloader') }}"
calibre_web_automated_downloader_role_dns_zone: "{{ lookup('role_var', '_web_domain', role='calibre_web_automated_downloader') }}"
calibre_web_automated_downloader_role_dns_proxy: "{{ dns_proxied }}"

################################
# Traefik
################################

calibre_web_automated_downloader_role_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"
calibre_web_automated_downloader_role_traefik_middleware_default: "{{ traefik_default_middleware }}"
calibre_web_automated_downloader_role_traefik_middleware_custom: ""
calibre_web_automated_downloader_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
calibre_web_automated_downloader_role_traefik_enabled: true
calibre_web_automated_downloader_role_traefik_api_enabled: false
calibre_web_automated_downloader_role_traefik_api_endpoint: ""

################################
# THEME
################################

calibre_web_automated_downloader_role_themepark_enabled: false
calibre_web_automated_downloader_role_themepark_theme: "{{ global_themepark_theme }}"
calibre_web_automated_downloader_role_themepark_domain: "{{ global_themepark_domain }}"

################################
# Docker
################################

calibre_web_automated_downloader_role_docker_container: "{{ calibre_web_automated_downloader_name }}"

# Image
calibre_web_automated_downloader_role_docker_image_pull: true
calibre_web_automated_downloader_role_docker_image_tag: "latest"
calibre_web_automated_downloader_role_docker_image_repo: "ghcr.io/calibrain/calibre-web-automated-book-downloader"
calibre_web_automated_downloader_role_docker_image: "{{ lookup('role_var', '_docker_image_repo', role='calibre_web_automated_downloader') }}:{{ lookup('role_var', '_docker_image_tag', role='calibre_web_automated_downloader') }}"

# Ports
calibre_web_automated_downloader_role_docker_ports_defaults: []
calibre_web_automated_downloader_role_docker_ports_custom: []
calibre_web_automated_downloader_role_docker_ports: "{{ lookup('role_var', '_docker_ports_defaults', role='calibre_web_automated_downloader')
                                                     + lookup('role_var', '_docker_ports_custom', role='calibre_web_automated_downloader') }}"

# Envs
calibre_web_automated_downloader_role_docker_envs_default:
  UID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  BOOK_LANGUAGE: "{{ lookup('role_var', '_book_language', role='calibre_web_automated_downloader') }}"
calibre_web_automated_downloader_role_docker_envs_custom: {}
calibre_web_automated_downloader_role_docker_envs: "{{ lookup('role_var', '_docker_envs_default', role='calibre_web_automated_downloader')
                                                     | combine(lookup('role_var', '_docker_envs_custom', role='calibre_web_automated_downloader')) }}"

# Commands
calibre_web_automated_downloader_role_docker_commands_default: []
calibre_web_automated_downloader_role_docker_commands_custom: []
calibre_web_automated_downloader_role_docker_commands: "{{ lookup('role_var', '_docker_commands_default', role='calibre_web_automated_downloader')
                                                        + lookup('role_var', '_docker_commands_custom', role='calibre_web_automated_downloader') }}"

# Volumes
calibre_web_automated_downloader_role_docker_volumes_default:
  - "{{ lookup('role_var', '_cwa_db_path', role='calibre_web_automated_downloader') }}:/auth/app.db:ro"
  - "{{ lookup('role_var', '_ingest_path', role='calibre_web_automated_downloader') }}:/cwa-book-ingest"
calibre_web_automated_downloader_role_docker_volumes_custom: []
calibre_web_automated_downloader_role_docker_volumes: "{{ lookup('role_var', '_docker_volumes_default', role='calibre_web_automated_downloader')
                                                       + lookup('role_var', '_docker_volumes_custom', role='calibre_web_automated_downloader')
                                                       + docker_volumes_downloads_common }}"

# Devices
calibre_web_automated_downloader_role_docker_devices_default: []
calibre_web_automated_downloader_role_docker_devices_custom: []
calibre_web_automated_downloader_role_docker_devices: "{{ lookup('role_var', '_docker_devices_default', role='calibre_web_automated_downloader')
                                                       + lookup('role_var', '_docker_devices_custom', role='calibre_web_automated_downloader') }}"

# Hosts
calibre_web_automated_downloader_role_docker_hosts_default: {}
calibre_web_automated_downloader_role_docker_hosts_custom: {}
calibre_web_automated_downloader_role_docker_hosts: "{{ docker_hosts_common
                                                     | combine(lookup('role_var', '_docker_hosts_default', role='calibre_web_automated_downloader'))
                                                     | combine(lookup('role_var', '_docker_hosts_custom', role='calibre_web_automated_downloader')) }}"

# Labels
calibre_web_automated_downloader_role_docker_labels_default: {}
calibre_web_automated_downloader_role_docker_labels_custom: {}
calibre_web_automated_downloader_role_docker_labels: "{{ docker_labels_common
                                                      | combine(lookup('role_var', '_docker_labels_default', role='calibre_web_automated_downloader'))
                                                      | combine(lookup('role_var', '_docker_labels_custom', role='calibre_web_automated_downloader')) }}"

# Hostname
calibre_web_automated_downloader_role_docker_hostname: "{{ calibre_web_automated_downloader_name }}"

# Networks
calibre_web_automated_downloader_role_docker_networks_alias: "{{ calibre_web_automated_downloader_name }}"
calibre_web_automated_downloader_role_docker_networks_default: []
calibre_web_automated_downloader_role_docker_networks_custom: []
calibre_web_automated_downloader_role_docker_networks: "{{ docker_networks_common
                                                        + lookup('role_var', '_docker_networks_default', role='calibre_web_automated_downloader')
                                                        + lookup('role_var', '_docker_networks_custom', role='calibre_web_automated_downloader') }}"

# Capabilities
calibre_web_automated_downloader_role_docker_capabilities_default: []
calibre_web_automated_downloader_role_docker_capabilities_custom: []
calibre_web_automated_downloader_role_docker_capabilities: "{{ lookup('role_var', '_docker_capabilities_default', role='calibre_web_automated_downloader')
                                                            + lookup('role_var', '_docker_capabilities_custom', role='calibre_web_automated_downloader') }}"

# Security Opts
calibre_web_automated_downloader_role_docker_security_opts_default: []
calibre_web_automated_downloader_role_docker_security_opts_custom: []
calibre_web_automated_downloader_role_docker_security_opts: "{{ lookup('role_var', '_docker_security_opts_default', role='calibre_web_automated_downloader')
                                                             + lookup('role_var', '_docker_security_opts_custom', role='calibre_web_automated_downloader') }}"

# Restart Policy
calibre_web_automated_downloader_role_docker_restart_policy: unless-stopped

# State
calibre_web_automated_downloader_role_docker_state: started

# Healthcheck
calibre_web_automated_downloader_role_docker_healthcheck:
  test: ["CMD", "pyrequests", "http://localhost:8084/request/api/status"]
  interval: 30s
  timeout: 30s
  retries: 3
  start_period: 5s